export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;
export const BAMBORA_PAYMENT_ROUTE_PATH = import.meta.env.VITE_BAMBORA_PAYMENT_API_ROUTE;
export const STRIPE_PUBLISHED_KEY = import.meta.env.VITE_STRIPE_PUBLISHED_KEY;


export const CREATE_STRIPE_PAYMENT_INTENT_ROUTE = import.meta.env.VITE_STRIPE_CREATE_PAYMENT_INTENT_API_ROUTE
export const CREATE_STRIPE_CREATE_PAYMENT_ROUTE = import.meta.env.VITE_STRIPE_CREATE_PAYMENT_API_ROUTE